//
//  SignInRouter.swift
//  Pods
//
//  Created Rystem Asqar on 4/28/24.
//  Copyright © 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Dastan Makhutov @mchutov
//

import UIKit
import CommonUI
import TabBar

public final class SignInRouter: SignInWireframeProtocol {
    weak var viewController: UIViewController?
    
    public static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = SignInViewController()
        let interactor = SignInInteractor()
        let router = SignInRouter()
        let presenter = SignInPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
    
    func routeToDashboardViewController() {
        if let sceneDelegate = UIApplication.shared.connectedScenes.first?.delegate as? RootViewControllerChangerProtocol {
            let tabBarVC = TabBarRouter.build()
            sceneDelegate.changeRootViewController(to: tabBarVC, animated: true)
        }
    }
}
