//
//  SignInProtocols.swift
//  Pods
//
//  Created Rystem Asqar on 4/28/24.
//  Copyright © 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Dastan Makhutov @mchutov
//

import Foundation

//MARK: Wireframe -
protocol SignInWireframeProtocol: AnyObject {
    func routeToDashboardViewController()
}
//MARK: Presenter -
protocol SignInPresenterProtocol: AnyObject {
    func setEmailProperty(_ isValid: Bool)
    func setPasswordProperty(_ isValid: Bool)
    func isValidEmail() -> Bool?
    func isValidPassword() -> Bool?
    func didTapLoginButton(withEmail email: String?, password: String?)
    func loginSuccessful()
    func loginError(_ error: Error)
}

//MARK: Interactor -
protocol SignInInteractorProtocol: AnyObject {
    var presenter: SignInPresenterProtocol?  { get set }
    var isValidEmail: Bool { get set }
    var isValidPassword: Bool { get set }
    func loginUser(email: String, password: String)
}

//MARK: View -
protocol SignInViewProtocol: AnyObject {
    var presenter: SignInPresenterProtocol?  { get set }
    func showAlert(alert: UIAlertController)
}
