//
//  SignInInteractor.swift
//  Pods
//
//  Created Rystem Asqar on 4/28/24.
//  Copyright © 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Dastan Makhutov @mchutov
//

import UIKit
import AppNetwork

public enum SignInDependencies {
    public static var signInProvider: AuthenticationProviderProtocol!
}

final class SignInInteractor {
    var isValidEmail = false
    var isValidPassword = false
    weak var presenter: SignInPresenterProtocol?
}

extension SignInInteractor: SignInInteractorProtocol {
    func loginUser(email: String, password: String) {
        SignInDependencies.signInProvider.loginUser(
            withEmail: email,
            password: password,
            success: {
                print("logged in")
                self.presenter?.loginSuccessful()
            },
            failure: { error in
                self.presenter?.loginError(error)
            }
        )
    }
    
    
}
